apiVersion: batch/v1
kind: CronJob
metadata:
  name: kill-random-node
  namespace: haloperidol
spec:
  # Hourly at 15 minutes past the hour
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: kill-random-node
        spec:
          serviceAccountName: haloperidol-sa
          containers:
          - name: kill-random-node
            image: bitnami/kubectl:latest
            command:
            - /scripts/run-kill-random-node.sh
            volumeMounts:
              - name: scripts
                mountPath: /scripts/
          restartPolicy: Never
          volumes:
          - name: scripts
            configMap:
              # This name must match the configMapGenerator. Kustomize will
              # append a hash to this name based on the content of the scripts
              name: scripts
              defaultMode: 0777
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-snapshots
  namespace: haloperidol
spec:
  # Hourly at 25 minutes past the hour
  schedule: "25 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: run-snapshots
            # These labels are needed to bypass the NetworkPolicy
            app: cluster-manager
            cluster-id: haloperidol
            customer-id: haloperidol
        spec:
          containers:
          - name: run-snapshots
            image: nixery.dev/shell/curl/jq/busybox
            env:
            - name: QDRANT_URL
              value: http://qdrant-haloperidol.haloperidol.svc.cluster.local:6333
            command:
            - /scripts/run-snapshots.sh
            volumeMounts:
              - name: scripts
                mountPath: /scripts/
          restartPolicy: Never
          volumes:
          - name: scripts
            configMap:
              # This name must match the configMapGenerator. Kustomize will
              # append a hash to this name based on the content of the scripts
              name: scripts
              defaultMode: 0777
