# Using a podmonitor since the headless service causes duplicatation
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: qdrant-haloperidol
  namespace: haloperidol
  labels:
    app.kubernetes.io/name: haloperidol
spec:
  selector:
    matchLabels:
      app: qdrant
      cluster-id: haloperidol
      customer-id: haloperidol
  namespaceSelector:
    matchNames:
    - haloperidol
  podMetricsEndpoints:
  - port: rest
    interval: 30s
