apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: haloperidol-role
  namespace: haloperidol
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["qdrant.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: haloperidol-rolebinding
  namespace: haloperidol
subjects:
- kind: ServiceAccount
  name: haloperidol-sa
  namespace: haloperidol
roleRef:
  kind: Role
  name: haloperidol-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haloperidol
  namespace: haloperidol
