name: Collect cluster stats

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-hcloud.sh
      - name: Collect and store cluster and bfb status
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          bash -x tools/check-bfb-health.sh
          bash -x tools/collect-node-metrics.sh
