name: Run snapshots

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"

jobs:
  run-snapshots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_url: [${{ secrets.QDRANT_CLUSTER_URL }}, ${{ secrets.QDRANT_CLUSTER_URL_2 }}]
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-tools.sh
          bash -x tools/ci/install-hcloud.sh
      - name: Run snapshots
        id: run_snapshots
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ matrix.cluster_url }}
          bash -x tools/run-snapshots.sh
      - name: Fail job if any check failed
        if: steps.run_snapshots.outputs.failed == 'true'
        run: exit 1
