name: Update BFB Upload

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  update-bfb-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-tools.sh
          bash -x tools/ci/install-hcloud.sh
      - name: Update bfb
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL }}
          export QC_NAME="qdrant-$(echo $QDRANT_CLUSTER_URL | sed -E 's~([^.]+)\..*~\1~')"
          bash -x tools/run-bfb-upload.sh

  update-bfb-upload-debug-cluster:
    if: ${{ vars.ENABLE_DEBUG_CLUSTER == 'true' }}
    needs: update-bfb-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-tools.sh
          bash -x tools/ci/install-hcloud.sh
      - name: Update bfb
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL_2 }}
          export QC_NAME="qdrant-$(echo $QDRANT_CLUSTER_URL | sed -E 's~([^.]+)\..*~\1~')"
          bash -x tools/run-bfb-upload.sh

  update-bfb-upload-3-cluster:
    if: ${{ vars.ENABLE_DEBUG_CLUSTER == 'true' }}
    needs: update-bfb-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-tools.sh
          bash -x tools/ci/install-hcloud.sh
      - name: Update bfb
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL_3 }}
          export QC_NAME="qdrant-$(echo $QDRANT_CLUSTER_URL | sed -E 's~([^.]+)\..*~\1~')"
          bash -x tools/run-bfb-upload.sh          
