#name: Update collect stats script on a remote server
#
#on:
#  push:
#    branches:
#      - master
#  repository_dispatch:
#  workflow_dispatch:
#    inputs:
#      server_name:
#          description: "Server to run the collect stats script on"
#          default: qdrant-manager
#      bg_task_name:
#          description: "Unique name for the background task"
#          default: collect-stats
#      qdrant_python_client_version:
#          description: "Qdrant python client version"
#          default: 1.12.1
#
#  schedule:
#    - cron: "20 23 * * *"
#
#
#jobs:
#  update-collect-stats:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: webfactory/ssh-agent@v0.8.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#      - name: Install tools
#        run: |
#          bash -x tools/ci/install-tools.sh
#          bash -x tools/ci/install-hcloud.sh
#      - name: Update collect stats script
#        run: |
#          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
#          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL }}
#          export QC_NAME="qdrant-$(echo $QDRANT_CLUSTER_URL | sed -E 's~([^.]+)\..*~\1~')"
#          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
#          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
#          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
#          export SERVER_NAME=${{ inputs.server_name }}
#          export BG_TASK_NAME=${{ inputs.bg_task_name }}
#          export QDRANT_PYTHON_CLIENT_VERSION=${{ inputs.qdrant_python_client_version }}
#          bash -x tools/run-collect-stats.sh
#
#  update-collect-stats-debug-cluster:
#    if: ${{ vars.ENABLE_DEBUG_CLUSTER == 'true' && ! cancelled() }}
#    needs: update-collect-stats
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: webfactory/ssh-agent@v0.8.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#      - name: Install tools
#        run: |
#          bash -x tools/ci/install-tools.sh
#          bash -x tools/ci/install-hcloud.sh
#      - name: Update collect stats script
#        run: |
#          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
#          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL_2 }}
#          export QC_NAME="qdrant-$(echo $QDRANT_CLUSTER_URL | sed -E 's~([^.]+)\..*~\1~')"
#          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
#          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
#          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
#          export SERVER_NAME=${{ inputs.server_name }}
#          export BG_TASK_NAME=${{ inputs.bg_task_name }}
#          export QDRANT_PYTHON_CLIENT_VERSION=${{ inputs.qdrant_python_client_version }}
#          bash -x tools/run-collect-stats.sh
#
#  update-collect-stats-three-cluster:
#    if: ${{ vars.ENABLE_DEBUG_CLUSTER == 'true' && ! cancelled() }}
#    needs: update-collect-stats-debug-cluster
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: webfactory/ssh-agent@v0.8.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#      - name: Install tools
#        run: |
#          bash -x tools/ci/install-tools.sh
#          bash -x tools/ci/install-hcloud.sh
#      - name: Update collect stats script
#        run: |
#          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
#          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL_3 }}
#          export QC_NAME="qdrant-$(echo $QDRANT_CLUSTER_URL | sed -E 's~([^.]+)\..*~\1~')"
#          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
#          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
#          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
#          export SERVER_NAME=${{ inputs.server_name }}
#          export BG_TASK_NAME=${{ inputs.bg_task_name }}
#          export QDRANT_PYTHON_CLIENT_VERSION=${{ inputs.qdrant_python_client_version }}
#          bash -x tools/run-collect-stats.sh