name: Update BFB Search

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "10 23 * * *"

jobs:
  update-bfb-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-tools.sh
          bash -x tools/ci/install-hcloud.sh
      - name: Update bfb
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ secrets.QDRANT_CLUSTER_URL }}
          bash -x tools/run-bfb-search.sh
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2