name: Update BFB Upload

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # At 20th minute of every 3rd hour
    - cron: "20 */3 * * *"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-cluster-urls.outputs.matrix }}
    steps:
      - id: set-cluster-urls
        run: |
          echo "matrix={\"url\":[\"${{ secrets.QDRANT_CLUSTER_URL }}\",\"${{ secrets.QDRANT_CLUSTER_URL_2 }}\"]}" >> $GITHUB_OUTPUT

  update-bfb-upload:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install tools
        run: |
          bash -x tools/ci/install-tools.sh
          bash -x tools/ci/install-hcloud.sh
      - name: Update bfb
        run: |
          export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
          export QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
          export QDRANT_CLUSTER_URL=${{ matrix.cluster_url }}
          bash -x tools/run-bfb-upload.sh         
